# Generated by Django 5.0.2 on 2024-03-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=30)),
            ],
        ),
    ]
