# Generated by Django 5.0.2 on 2024-03-03 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_users_email_alter_users_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='users_profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=30)),
                ('escolar', models.BooleanField()),
                ('benjamin', models.BooleanField()),
                ('cadete', models.BooleanField()),
                ('junior', models.BooleanField()),
                ('estudiante', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
