# Generated by Django 5.0.2 on 2024-03-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_users_profiles_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_profiles',
            name='password',
        ),
    ]
