# Generated by Django 5.0.2 on 2024-03-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_users_profiles_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_profiles',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
