# Generated by Django 5.0.2 on 2024-03-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_users_profiles_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_profiles',
            name='benjamin_mark',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='users_profiles',
            name='cadete_mark',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='users_profiles',
            name='escolar_mark',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='users_profiles',
            name='estudiante_mark',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='users_profiles',
            name='junior_mark',
            field=models.FloatField(default=0),
        ),
    ]
