# Generated by Django 5.0.2 on 2024-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_rename_sex_users_profiles_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_profiles',
            name='benjamin_mark',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users_profiles',
            name='cadete_mark',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users_profiles',
            name='escolar_mark',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users_profiles',
            name='estudiante_mark',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users_profiles',
            name='junior_mark',
            field=models.FloatField(),
        ),
    ]
