# Generated by Django 5.0.2 on 2024-03-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_users_profiles_benjamin_mark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_profiles',
            old_name='schoolType',
            new_name='school_type',
        ),
    ]
