# Generated by Django 5.0.2 on 2024-03-10 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_usuarios_delete_users_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_telefono', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=100)),
                ('escuela', models.CharField(max_length=120)),
                ('tipo_escuela', models.CharField(max_length=10)),
                ('grado_academico', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolar', models.BooleanField()),
                ('benjamin', models.BooleanField()),
                ('cadete', models.BooleanField()),
                ('junior', models.BooleanField()),
                ('estudiante', models.BooleanField()),
                ('calificacion_escolar', models.FloatField(default=0.0, null=True)),
                ('calificacion_benjamin', models.FloatField(default=0.0, null=True)),
                ('calificacion_cadete', models.FloatField(default=0.0, null=True)),
                ('calificacion_junior', models.FloatField(default=0.0, null=True)),
                ('calificacion_estudiante', models.FloatField(default=0.0, null=True)),
                ('id_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.estudiantes')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
