# Generated by Django 5.0.2 on 2024-03-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_estudiantes_examenes_delete_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
